error handling

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -11,7 +11,9 @@ jobs:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v2
-      - run: npm ci && npm run build
+      - name: Putting backend main url in file
+        run: sed -i "1s|.*|const backend='https://mysterious-savannah-09391.herokuapp.com/'|" src/env.js
+      - run: npm ci && npx eslint src && npm run build
       - uses: FirebaseExtended/action-hosting-deploy@v0
         with:
           target: production
@@ -21,3 +23,21 @@ jobs:
           projectId: default
         env:
           FIREBASE_CLI_PREVIEWS: hostingchannels
+  Create-issues-using-TODO:
+    runs-on: self-hosted
+    steps:
+      - uses: actions/checkout@v2
+        with:
+            fetch-depth: 2
+
+      - name: Github login
+        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
+
+      - name: Creating issues
+        run: readarray -t array <<< $(git diff HEAD^ --name-only -G "TODO" -- ':!:*.yml' | xargs --no-run-if-empty git
+                grep -n "TODO" --) && for command in "${array[@]}"; do
+                    gh issue create --title "${command##*:}" --body "${command}" --label "todo" || echo "ERROR ${command}";
+                      done
+
+      - name: Github logout
+        run: gh auth logout --hostname github.com
