Bugs resolved

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -24,6 +24,7 @@ jobs:
   Create-issues-using-TODO:
     runs-on: self-hosted
     needs: build_and_deploy
+  - uses: actions/checkout@v2
     steps:
       - name: Github login
         run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
@@ -31,7 +32,7 @@ jobs:
       - name: Creating issues
         run: readarray -t array <<< $(git diff HEAD^ --name-only -G "TODO" -- ':!:*.yml' | xargs --no-run-if-empty git
                 grep -n "TODO" --) && for command in "${array[@]}"; do
-                    gh issue create --title "${command##*#}" --body "${command}" --label "todo" || echo "ERROR $(command)";
+                    gh issue create --title "${command##*#}" --body "${command}" --label "todo" || echo "ERROR ${command}";
                       done
 
       - name: Github logout
