Searchterm working

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -21,3 +21,18 @@ jobs:
           projectId: development
         env:
           FIREBASE_CLI_PREVIEWS: hostingchannels
+  Create-issues-using-TODO:
+    runs-on: self-hosted
+    needs: build_and_deploy
+    steps:
+      - name: Github login
+        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
+
+      - name: Creating issues
+        run: readarray -t array <<< $(git diff HEAD^ --name-only -G "TODO" -- ':!:*.yml' | xargs --no-run-if-empty git
+                grep -n "TODO" --) && for command in "${array[@]}"; do
+                    gh issue create --title "${command##*#}" --body "${command}" --label "todo" || echo "ERROR $(command)";
+                      done
+
+      - name: Github logout
+        run: gh auth logout --hostname github.com
